FROM postgres:14.2-alpine

# ARG USER_ID
# ARG GROUP_ID

# RUN addgroup --gid $GROUP_ID user
# RUN adduser --disabled-password --gecos '' --uid $USER_ID -G user user

# RUN chown -R user:user /var/lib/postgresql/data