version: "3.8"

x-database_environment_data: &database_environment_data
  environment:
  - POSTGRES_DB=${DATABASE_NAME}
  - POSTGRES_USER=${DATABASE_USER}
  - POSTGRES_PASSWORD=${DATABASE_PASSWORD}

services:
  postgres:
    container_name: "${PROJECT_PREFIX}-postgres"
    build:
      context: .
      dockerfile: ./docker/postgres/Dockerfile
      args:
         USER_ID: ${USER_ID:-1000}
         GROUP_ID: "${GROUP_ID:-1000}"
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
    ports:
      - "${DATABASE_EXTERNAL_PORT}:5432"
    <<: *database_environment_data
  postgres_test:
    container_name: "${PROJECT_PREFIX}-postgres-test"
    image: postrr_postgres
    ports:
      - "${DATABASE_TEST_EXTERNAL_PORT}:5432"
    <<: *database_environment_data
  ruby:
    container_name: "${PROJECT_PREFIX}-ruby"
    build:
      context: .
      dockerfile: ./docker/ruby/Dockerfile
      args:
         USER_ID: ${USER_ID:-1000}
         GROUP_ID: "${GROUP_ID:-1000}"
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/atmosphere
    ports:
      - "${API_EXTERNAL_PORT}:3000"
    depends_on:
      - postgres